
## 第一部分： 基础信息
name: chip_d1                                    # <必选项> 包名称 （符合C语言变量命名规则），长度少于等于64字节
version: flashelf                                 # <必选项> 组件版本号
description: driver & sdk for platform/mcu d1  chip         # <必选项> 建议至少20字以上
type: chip                                          # <必选项> 组件类型，为：solution, chip, board, common, sdk

tag: 核心模块                                       # <可选项> 组件分类，缺省值： ''
keywords:                                           # <可选项> 标签，会影响到组件被搜索的效果，合理的标签很重要
  - base
license: Apache license v2.0                        # <可选项> 源代码的许可证，要确保所有代码、文件的许可证不冲突。如：MIT，Apache license v2.0，BSD

#           指定该组件依赖的组件及版本，版本支持条件比较，支持：>=v1.0, >v1.0, ==v1.0, <=v1.0, <v1.0, v1.0
#           未指定条件时，默认为 ==，如 v1.0 与 ==v1.0
# depends:                                 # <可选项> 该组件依赖其他的组件，合理的依赖才能保证组件能编译、使用
#   - minilibc: v7.2.0
#   - aos: >=v7.2.0

hw_info:
  arch_name: riscv
  cpu_name: c906fdv
  toolchain_prefix: riscv64-unknown-elf
  vendor_name: allwinner
  ld_script: gcc_flash.ld
  flash_program: d1_flash.elf

## 第四部分：编译连接信息
# build_config:                            # <可选项> 编译配置项
#   include:                               # <可选项> 编译时，影响编译器的-I 参数 ,全局有效
#     - src                                #        include 只能是该软件包下的目录，不能使用外部目录
#   internal_include:                      # <可选项> 编译时，影响编译器的-I 参数 ,组件内有效
#     - include
#   cflag: ''                              # <可选项> C 编译器所需要要的编译参数
#   cxxflag: ''                            # <可选项> CXX 编译器所需要要的编译参数
#   asmflag: ''                            # <可选项> 汇编器所需要要参数
#   define:                                # <可选项> 宏定义, 增加编译器的-D 选项,如：
#     XXX: 1                               #   -DXXX=1
#     AAA: 1                               #   -DAAA
#     STR: "abc"                           #   -DSTR="abc"
#   libs:                                  # 该组件中支持的二进制静态库,如：libxxx.a, libyyy.a
#     - xxx                                #   -lxxx
#     - yyy                                #   -lyyy
#   libpath:                               # 指定静态库所在的路径（相对于该组件路径）
#     - libs                               #   -Llibs
build_config:
  cflag:
  cxxflag:
  ldflag:
  asmflag: -D__ASSEMBLY__
  include:
    - include/
    - melis/hal/source
    - melis/misc/video
    - melis/misc/
    - melis/include/osal
    - melis/include/hal
  internal_include:
    - melis/hal/source
    - melis/hal/source/gpio
    - melis/hal/source/ccmu/sunxi-ng
    - melis/hal/source/ccmu/
    - melis/hal/source/rtc
    - melis/hal/source/dma
    - melis/hal/source/pwm
    - melis
    - sys/d1
    - sys
    - drivers/ll

# source_file:                             # <可选项> 指定参与编译的源代码文件，支持通配符，采用相对路径
#   - src/*.c                              # 例：组件 src 目录下所有的扩展名为 c 的源代码文件
source_file:
  - sys/*.c
  - sys/d1/*.c
  - sys/startup.S
  - sys/dispatcher_s.S
  - sys/dispatcher_boot.S
  - drivers/spi.c
  - drivers/uart.c
  - drivers/dw_uart_ll.c
  - drivers/spinorflash.c
  - drivers/wdt.c
  - drivers/rtc.c
  - drivers/gpio_pin.c
  - drivers/gpio.c
  - drivers/iic.c
  - drivers/dma.c
  - drivers/timer.c
  - drivers/irq_port.c
  - aos_pcm.c
  - xr829_devops.c ? <CONFIG_AOS_LWIP>

  - melis/hal/source/common/*.c
  - melis/hal/source/ccmu/hal_reset.c
  - melis/hal/source/ccmu/hal_clk.c
  - melis/hal/source/gpio/sun8iw20/*.c
  - melis/hal/source/gpio/*.c
  - melis/hal/source/dma/*.c
  - melis/hal/source/spi/*.c
  - melis/hal/source/spinor/*.c
  - melis/hal/source/watchdog/*.c
  - melis/hal/source/rtc/*.c
  - melis/hal/source/timer/hal_timer.c
  - melis/hal/source/timer/sunxi_timer.c
  - melis/hal/source/pwm/*.c

  # - melis/hal/source/ccmu/sunxi-ng/*.c
  - melis/hal/source/ccmu/sunxi-ng/clk.c
  - melis/hal/source/ccmu/sunxi-ng/ccu.c
  - melis/hal/source/ccmu/sunxi-ng/clk-fixed-rate.c
  - melis/hal/source/ccmu/sunxi-ng/ccu-sun8iw20-r.c
  - melis/hal/source/ccmu/sunxi-ng/ccu-sun8iw20-rtc.c
  - melis/hal/source/ccmu/sunxi-ng/ccu-sun8iw20.c
  - melis/hal/source/ccmu/sunxi-ng/ccu_gate.c
  - melis/hal/source/ccmu/sunxi-ng/ccu_div.c
  - melis/hal/source/ccmu/sunxi-ng/ccu_frac.c
  - melis/hal/source/ccmu/sunxi-ng/ccu_mp.c
  - melis/hal/source/ccmu/sunxi-ng/ccu_sdm.c
  - melis/hal/source/ccmu/sunxi-ng/ccu_common.c
  - melis/hal/source/ccmu/sunxi-ng/ccu_reset.c
  - melis/hal/source/ccmu/sunxi-ng/clk-fixed-factor.c
  - melis/hal/source/ccmu/sunxi-ng/ccu_mux.c
  - melis/hal/source/ccmu/sunxi-ng/clk-fixed-factor.c
  - melis/hal/source/ccmu/sunxi-ng/ccu_mult.c
  - melis/hal/source/ccmu/sunxi-ng/ccu_nm.c
  - melis/hal/source/ccmu/sunxi-ng/ccu_nkmp.c
  - melis/hal/source/ccmu/sunxi-ng/clk-divider.c

  - melis/osal/src/*.c
  - melis/misc/*.c

## 第五部分：配置信息
# def_config:                              # 组件的可配置项
#   CONFIG_DEBUG: y
#   CONFIG_PARAM_NOT_CHECK: y
#   CONFIG_CLI: y
def_config:
  CONFIG_LOG_DEFAULT_LEVEL: 0
  HAVE_INIT_ARRAY_LD: y
  CONFIG_NON_ADDRESS_FLASH: y
  CONFIG_CSI_V2: 1
  CONFIG_CSI: "csi2"
  CONFIG_CPU_C906: y
  CONFIG_ARCH_INTERRUPTSTACK: 4096
  CONFIG_SOC_SUN20I: 1
  CONFIG_SOC_SUN20IW1: 1
  CONFIG_SOC_SUN20IW1P1: 1
  CONFIG_ARCH_SUN20IW1: 1
  CONFIG_DRIVERS_SUNXI_CCU: 1   # common_ccmu.h
  # SPINOR
  CONFIG_SUNXI_SPI_CPU_XFER_ONLY: 1 # SPI not DMA
  CONFIG_DRIVERS_SPINOR_FREQ: 50
  CONFIG_DRIVERS_SPINOR_4K_SECTORS: 1
  #
  # CONFIG_U_FLASH_CORE: 1

  # MTD partition config to support mtd vfs apis(open/close/read/write/ioctl).
  # MTD_PART_ID_FS:        0
  # MTD_PART_ID_KV:        1
  # SOUND
  CONFIG_DRIVERS_DMA: 1
  CONFIG_DRIVERS_SOUND: 1
  CONFIG_SND_CODEC_SUN8IW20_AUDIOCODEC: 1
  CONFIG_SND_PLATFORM_SUNXI_PCM: 1
  CONFIG_SND_PLATFORM_SUNXI_CPUDAI: 1
  CONFIG_SND_PLATFORM_SUNXI_DAUDIO: 1
  # CONFIG_SND_PLATFORM_SUNXI_DAUDIO0: 1
  CONFIG_BUILTIN_WAV_FILE: 1
  CONFIG_SND_PLATFORM_SUNXI_DMIC: 1
  # DISPLAY
  CONFIG_LCD_SUPPORT_TFT08006: 1
  MIPI_DSI_IP_VERSION: 40
  CONFIG_DISP2_SUNXI_SUPPORT_ENAHNCE: 1
  CONFIG_SUNXI_DISP2_FB_DISABLE_ROTATE: 1
  # TOUCH
  CONFIG_DRIVERS_TOUCH: 1
  #wifi x829
  CONFIG_BACKEND_XRADIO: 1
  CONFIG_DRIVER_XRADIO: 1
  CONFIG_CRYPTO_INTERNAL: 1
  CONFIG_NO_RANDOM_POOL: 1
  CONFIG_NO_CONFIG_BLOBS: 1
  CONFIG_NO_ROAMING: 1
  CONFIG_NO_RADIUS: 1
  CONFIG_NO_ACCOUNTING: 1
  CONFIG_NO_VLAN: 1
  CONFIG_NO_CTRL_IFACE: 1
  CONFIG_XR829: 1
  CONFIG_OS_NUTTX: 1
  CONFIG_OS_NUTTX_CM_PASS: 1
  CONFIG_AOS: 1
  CONFIG_USE_SDIO: 1
  CONFIG_DETECT_CARD: 1
  CONFIG_USE_SD: 1
## 第六部分：安装信息
# install:
#   - dest: include/                       # 安装的目的路径 dest是相当路径，通常是相对于YoC SDK 安装目录
#     source:                              # 安装源列表
#      - src/*.h                           # 支持通配符，相对路径


## 第七部分：导出部分
# export:
#   - dest: "<SOLUTION_PATH>/generated/data" # 安装的目的路径 dest是相当路径
#     source:                                # 安装源列表
#       - "bootimgs/boot"
#       - "bootimgs/tee"
#       - "bootimgs/mtb"
#       - "configs/config.yaml"
